CREATE DATABASE QL_BANHANG

USE QL_BANHANG

CREATE TABLE KHACHHANG(
	MAKH VARCHAR(10) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(15)
);
CREATE TABLE MATHANG(
	MAMH VARCHAR(10) PRIMARY KEY NOT NULL,
	TENMH NVARCHAR(100), 
	DVT NVARCHAR(100),
	NUOCSX NVARCHAR(100)
);
CREATE TABLE HOADON(
	SOHD VARCHAR(10) PRIMARY KEY NOT NULL,
	NGAYLAPHD DATE, 
	NGAYGIAODK DATE,
	MAKH VARCHAR(10),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)	
);
CREATE TABLE CTHOADON(
	SOHD VARCHAR(10),
	MAMH VARCHAR(10),
	SOLUONG INT,
	DONGIA DECIMAL(18,0),
	CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_CTHOADON_MATHANG FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
);