CREATE DATABASE QL_PHONGTRAO_Bai8

USE QL_PHONGTRAO_Bai8

CREATE TABLE PHONG(
	MAPH VARCHAR(10) NOT NULL,
	TENPHONG NVARCHAR(10), 
	MANQL VARCHAR(10)
	CONSTRAINT PK_PHONG PRIMARY KEY (MAPH)
);
CREATE TABLE NHANVIEN(
	MANV VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(100), 
	NGAYSINH DATE,
	PHAI NVARCHAR(5),
	MAPH VARCHAR(10),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
	CONSTRAINT FK_NHANVIEN_PHONG FOREIGN KEY (MAPH) REFERENCES PHONG(MAPH)
);
CREATE TABLE TROCHOI(
	MATC VARCHAR(10) NOT NULL,
	TENTROCHOI NVARCHAR(100),
	NGAYCHOI DATE,
	SOLUONGDK INT,
	CONSTRAINT PK_TROCHOI PRIMARY KEY (MATC)
);
CREATE TABLE DANGKY(
	MANV VARCHAR(10),
	MATC VARCHAR(10),
	CONSTRAINT FK_DANGKY_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_DANGKY_TROCHOI FOREIGN KEY (MATC) REFERENCES TROCHOI(MATC)
);

--1. Cho biết danh sách nhân viên (MANV, HOTEN) của phòng ban có tên : N'Tài Chính' và có tuổi >= 50
--2. Cho biết danh sách nhân vien (MANV, HOTEN) tham gia từ 2 trò chơi trở lên
--3. Cho biết danh sách trò chơi (MATC, TENTROCHOI) mà không có nhân viên nào đăng kí