CREATE DATABASE QL_BANHANG

USE QL_BANHANG

CREATE TABLE KHACHHANG(
	MAKH VARCHAR(10) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(15)
);
CREATE TABLE MATHANG(
	MAMH VARCHAR(10) PRIMARY KEY NOT NULL,
	TENMH NVARCHAR(100), 
	DVT NVARCHAR(100),
	NUOCSX NVARCHAR(100)
);
CREATE TABLE HOADON(
	SOHD VARCHAR(10) PRIMARY KEY NOT NULL,
	NGAYLAPHD DATE, 
	NGAYGIAODK DATE,
	MAKH VARCHAR(10),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)	
);
CREATE TABLE CTHOADON(
	SOHD VARCHAR(10),
	MAMH VARCHAR(10),
	SOLUONG INT,
	DONGIA DECIMAL(18,0),
	CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_CTHOADON_MATHANG FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
);

--1.Liệt kê danh sách mặt hành không được sản xuất ở Việt Nam, MAMH, TENMH
SELECT MAMH, TENMH
FROM MATHANG
WHERE NUOCSX <> 'Việt Nam';
SELECT KHACHHANG.MAKH, HOTEN, DIACHI, DIENTHOAI, NGAYLAPHD
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE NGAYLAPHD BETWEEN '2022-06-01' AND '2022-06-30';
SELECT KHACHHANG.MAKH, HOTEN, DIACHI, DIENTHOAI, NGAYLAPHD
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE NGAYLAPHD BETWEEN '2022-06-01' AND '2022-06-30';
SELECT MATHANG.MAMH, TENMH, COUNT(SOHD) AS SOLUONG_HOADON
FROM MATHANG
LEFT JOIN CTHOADON ON MATHANG.MAMH = CTHOADON.MAMH
GROUP BY MATHANG.MAMH, TENMH;
SELECT MATHANG.MAMH, TENMH
FROM MATHANG
JOIN CTHOADON ON MATHANG.MAMH = CTHOADON.MAMH
GROUP BY MATHANG.MAMH, TENMH
ORDER BY SUM(SOLUONG) DESC

--2.Cho biết các khách hàng có mua hàng trong tháng 6 năm 2022(NGAYLAPHD từ 01/06/2022 đến 30/06/2022), thông tin gồm
-- MAKH, HOTEN, DIACHI, DIENTHOAI, NGAYLAPHD
--3. Hiện thị danh sách mặt hàng(MAMH, TENMH) và số lượng hóa đơn có bán mặt hàng đó. Lưu ý: mặt hàng nào chưa bán thì hiện thị số lượng là 0
--4. Cho biết mặt hàng(MAMH, TENMH) nào có tổng số lượng bán nhiều nhất
